services:
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - '${REDIS_DATA_VOLUME}:/data'
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'

  mongodb:
    image: mongo:7
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - '${MONGO_DATA_VOLUME}:/data/db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
